export const ROUTES = {
  LANDINGPAGE: "/",
  CONTATO: "/contato",
  VIAGEM: "/viagem",
  RELATORIO: "/relatorio/dashboard",
  VIAGENS_CADASTRADAS: "/relatorio/viagens-cadastradas",
  LOGIN: "/login",
  SIGNUP: "/cadastro",
  VALIDAR: "/validar",
  PRODUCT: "/produto",
  CADASTRAR_VIAGEM: "/Cadastrar-Viagem",
  BUSCAR_VIAGEM: "/buscar-viagem",
  CHECKOUT: "/checkout",
  CONFIRMACAO: "/confirmacao",
} as const;
